### ISSUE TITLE
command with nested command fails

### ISSUE THREAD

**Issue by Lt-Mayonesa** [redbeestudios/hexagon#37]
> hexagon version: 0.13.3

action:
```yaml
  - name: docker-clean-up
    type: shell
    alias: dcu
    long_name: Mantenimiento local de Docker
    description: Borra las imágenes dangling con status exit.
    action: docker rm -f $(docker container ls --filter "status=exited" -q)
```

error:
```bash
? Hi, which tool would you like to use today? ƒ Mantenimiento local de Docker                             Borra las imágenes dangling con status exit.
unknown flag: --filter
See 'docker rm --help'.
docker rm -f $(docker container ls --filter status=exited -q) returned 125

 We tried looking for:
   - Your CLI's custom_tools_dir: /home/joaco/src/todo-pago/devs
   - Hexagon repository of externals tools (hexagon.tools.external)
   - A known script file (.js, .sh)
   - Running your action as a shell command directly
```
